name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 9 Preview
        run: |
          wget https://download.visualstudio.microsoft.com/download/pr/46dbf1c3-32d2-47f0-bb17-d99f53475c0c/20c76bbd0d03b78681de649ed8e6c0bb/dotnet-sdk-9.0.100-rc.1.24452.12-linux-x64.tar.gz
          mkdir -p $HOME/dotnet
          tar zxf dotnet-sdk-9.0.100-rc.1.24452.12-linux-x64.tar.gz -C $HOME/dotnet
          echo "$HOME/dotnet" >> $GITHUB_PATH
          echo "DOTNET_ROOT=$HOME/dotnet" >> $GITHUB_ENV

      - name: Restore dependencies
        run: dotnet restore ./LMS.csproj

      - name: Build
        run: dotnet build ./LMS.csproj --configuration Release --no-restore

  frontend:
    runs-on: ubuntu-latest
    needs: backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend dependencies
        run: npm install
        working-directory: ./lms-client

      - name: Build frontend
        run: npm run build
        working-directory: ./lms-client
